### ISSUE TITLE
Update information about TI2V-Zero

### ISSUE THREAD

**Issue by nihaomiao** [Kobaayyy/Awesome-CVPR2024-AIGC#4]
Hi, @Kobaayyy,

Thanks a lot for your impressive work!

The code of our TI2V-Zero is available at this [link](https://github.com/merlresearch/TI2V-Zero).  Could you update the information on our paper?

Thanks again for your time!

**Comment by Kobaayyy** [comment]
> Hi, @Kobaayyy,
> 
> Thanks a lot for your impressive work!
> 
> The code of our TI2V-Zero is available at this [link](https://github.com/merlresearch/TI2V-Zero). Could you update the information on our paper?
> 
> Thanks again for your time!

Nice work! Thanks for your information, I have updated.
