### ISSUE TITLE
Update Physgen paper link

### ISSUE THREAD

**Issue by stevenlsw** [Kobaayyy/Awesome-CVPR2024-AIGC#8]
Hi, 

Thanks so much for the collection of amazing works. 

The PhysGen: Rigid-Body Physics-Grounded Image-to-Video Generation has its arxiv version at https://arxiv.org/abs/2409.18964 

Could you help to update the paper link in ECCV2024.md. 

Thanks again for the time and effort.

**Comment by Kobaayyy** [comment]
> Hi,
> 
> Thanks so much for the collection of amazing works.
> 
> The PhysGen: Rigid-Body Physics-Grounded Image-to-Video Generation has its arxiv version at https://arxiv.org/abs/2409.18964
> 
> Could you help to update the paper link in ECCV2024.md.
> 
> Thanks again for the time and effort.

Great work!Thanks for your information, I have updated.
